import type { Product, User, Order } from '@/types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Sith Lord Meditation Chamber (Miniature)',
    description: 'Find your focus and plot galactic domination with this exquisite miniature meditation chamber.',
    price: 199.99,
    imageUrl: '/images/products/sith_meditation_chamber.png', // Example for local image
    dataAiHint: 'sith chamber',
    category: 'Collectibles',
    stock: 10,
  },
  {
    id: '2',
    name: 'Customizable Lightsaber Hilt (Sith Edition)',
    description: 'Forge your path to power with a customizable lightsaber hilt, radiating dark side energy.',
    price: 299.99,
    imageUrl: '/images/products/sith_lightsaber_hilt.png', // Example for local image
    dataAiHint: 'sith lightsaber',
    category: 'Weaponry',
    stock: 5,
  },
  {
    id: '3',
    name: "Darth Vader's Helmet Replica (Wearable)",
    description: "Strike fear into the hearts of rebels with this life-size, wearable Darth Vader helmet replica.",
    price: 499.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'vader helmet',
    category: 'Armor',
    stock: 3,
  },
  {
    id: '4',
    name: "Kylo Ren's Command Shuttle Model",
    description: 'A detailed model of Kylo Ren\'s imposing Upsilon-class command shuttle. Intimidate your desk.',
    price: 149.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'kylo shuttle',
    category: 'Vehicles',
    stock: 15,
  },
  {
    id: '5',
    name: "Emperor Palpatine's Throne Replica (Desk Size)",
    description: 'Rule your domain from this meticulously crafted desk-sized replica of Emperor Palpatine\'s throne.',
    price: 249.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'emperor throne',
    category: 'Collectibles',
    stock: 8,
  },
  {
    id: '6',
    name: 'Set of Imperial Cog Coasters',
    description: 'Protect your surfaces with the might of the Empire. Set of 4 Imperial Cog coasters.',
    price: 29.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'imperial cog',
    category: 'Homeware',
    stock: 50,
  },
  {
    id: '7',
    name: '"Join the Dark Side" Propaganda Poster',
    description: 'Inspire loyalty and fear with this vintage-style "Join the Dark Side" propaganda poster.',
    price: 19.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dark side poster',
    category: 'Decor',
    stock: 100,
  },
  {
    id: '8',
    name: 'Death Star Blueprint Schematic Print',
    description: 'Detailed blueprint schematic of the ultimate power in the universe. A must-have for Imperial engineers.',
    price: 49.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'death star blueprint',
    category: 'Decor',
    stock: 30,
  },
  {
    id: '9',
    name: 'First Order Stormtrooper Armor Decal Kit',
    description: 'Upgrade your gear with this high-quality First Order Stormtrooper armor decal kit.',
    price: 39.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'stormtrooper armor',
    category: 'Accessories',
    stock: 25,
  },
  {
    id: '10',
    name: 'TIE Fighter Pilot Helmet Replica',
    description: 'Enlist in the Imperial Navy with this authentic TIE Fighter Pilot helmet replica.',
    price: 349.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'tie pilot helmet',
    category: 'Armor',
    stock: 7,
  },
  {
    id: '11',
    name: 'Sith Holocron Prop Replica',
    description: 'Unlock ancient Sith secrets with this intricately designed Holocron prop replica. (Knowledge not included).',
    price: 129.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'sith holocron',
    category: 'Collectibles',
    stock: 12,
  },
  {
    id: '12',
    name: 'Dark Rey Lightsaber Hilt (Foldable)',
    description: 'Embrace your destiny with this replica of Dark Rey\'s unique foldable lightsaber hilt.',
    price: 319.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dark rey lightsaber',
    category: 'Weaponry',
    stock: 6,
  },
  {
    id: '13',
    name: 'Knights of Ren Weapon Set (Miniatures)',
    description: 'A collection of miniature replicas of the varied and brutal weapons wielded by the Knights of Ren.',
    price: 89.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'knights ren weapons',
    category: 'Collectibles',
    stock: 18,
  },
  {
    id: '14',
    name: 'Imperial Officer Uniform Patch Set',
    description: 'Display your rank and allegiance with this set of authentic Imperial Officer uniform patches.',
    price: 24.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'imperial officer patch',
    category: 'Accessories',
    stock: 40,
  },
  {
    id: '15',
    name: '"Power! Unlimited Power!" Mug',
    description: 'Sip your favorite beverage and feel the surge of unlimited power with this Emperor-approved mug.',
    price: 15.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'palpatine mug',
    category: 'Homeware',
    stock: 75,
  },
  {
    id: '16',
    name: 'Grand Inquisitor Spinning Lightsaber Desk Toy',
    description: 'A mesmerizing desk toy replica of the Grand Inquisitor\'s double-bladed spinning lightsaber.',
    price: 79.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'inquisitor lightsaber',
    category: 'Collectibles',
    stock: 20,
  },
  {
    id: '17',
    name: 'Darth Maul Bust',
    description: 'Capture the menacing presence of Darth Maul with this highly detailed collectible bust.',
    price: 159.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'darth maul bust',
    category: 'Collectibles',
    stock: 9,
  },
  {
    id: '18',
    name: 'Asajj Ventress Curved Lightsabers (Display)',
    description: 'A pair of elegant, curved lightsaber hilts inspired by Asajj Ventress, perfect for display.',
    price: 279.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'ventress lightsabers',
    category: 'Weaponry',
    stock: 4,
  },
  {
    id: '19',
    name: 'Shadow Trooper Action Figure',
    description: 'Elite, stealthy, and enigmatic. Add the Shadow Trooper to your Imperial forces.',
    price: 34.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'shadow trooper',
    category: 'Action Figures',
    stock: 22,
  },
  {
    id: '20',
    name: 'Galactic Empire Insignia Pin',
    description: 'Wear your loyalty with pride. A high-quality metal pin of the Galactic Empire insignia.',
    price: 9.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'empire pin',
    category: 'Accessories',
    stock: 150,
  },
  {
    id: '21',
    name: 'Luke Skywalker\'s Lightsaber Hilt (ROTJ)',
    description: 'The iconic green lightsaber hilt used by Luke Skywalker in Return of the Jedi. A symbol of hope.',
    price: 289.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'luke lightsaber green',
    category: 'Weaponry',
    stock: 7,
  },
  {
    id: '22',
    name: 'Millennium Falcon Model Kit',
    description: 'Assemble the fastest hunk of junk in the galaxy. This detailed model kit is perfect for smugglers and rebels.',
    price: 179.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'millennium falcon model',
    category: 'Vehicles',
    stock: 10,
  },
  {
    id: '23',
    name: 'Princess Leia Organa Ceremonial Gown (Replica)',
    description: 'A stunning replica of Princess Leia\'s ceremonial gown from A New Hope. For regal occasions.',
    price: 399.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'leia gown',
    category: 'Apparel',
    stock: 3,
  },
  {
    id: '24',
    name: 'Han Solo\'s DL-44 Heavy Blaster Pistol Prop',
    description: 'The trusty sidearm of the galaxy\'s most charming scoundrel. Good for aggressive negotiations.',
    price: 249.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'han solo blaster',
    category: 'Weaponry',
    stock: 8,
  },
  {
    id: '25',
    name: 'R2-D2 Interactive Astromech Droid',
    description: 'Your very own loyal and resourceful astromech droid. Beeps, boops, and projects maps!',
    price: 599.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'r2d2 droid',
    category: 'Robotics',
    stock: 5,
  },
  {
    id: '26',
    name: 'Chewbacca\'s Bowcaster Prop Replica',
    description: 'A powerful and iconic Wookiee weapon. Requires strength and a good roar to wield effectively.',
    price: 329.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'chewbacca bowcaster',
    category: 'Weaponry',
    stock: 4,
  },
  {
    id: '27',
    name: 'Jedi Holocron Replica',
    description: 'A source of ancient Jedi wisdom and teachings. Meditate upon its light for guidance.',
    price: 119.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'jedi holocron',
    category: 'Collectibles',
    stock: 15,
  },
  {
    id: '28',
    name: 'Rebel Alliance Insignia Necklace',
    description: 'Show your support for the Rebellion with this elegant Starbird insignia necklace.',
    price: 49.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'rebel alliance necklace',
    category: 'Accessories',
    stock: 30,
  },
  {
    id: '29',
    name: 'Ahsoka Tano\'s Twin Lightsabers (Display)',
    description: 'The distinctive white-bladed lightsabers of the skilled warrior Ahsoka Tano. For display only.',
    price: 379.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'ahsoka lightsabers white',
    category: 'Weaponry',
    stock: 6,
  },
  {
    id: '30',
    name: 'Boba Fett Helmet (Weathered Edition)',
    description: 'The battle-scarred helmet of the galaxy\'s most feared bounty hunter. Includes dent.',
    price: 479.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'boba fett helmet',
    category: 'Armor',
    stock: 4,
  },
  {
    id: '31',
    name: 'Mandalorian Beskar Ingot Prop',
    description: 'A solid replica of a Beskar steel ingot, the prized currency and material of Mandalore.',
    price: 79.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'beskar ingot',
    category: 'Collectibles',
    stock: 20,
  },
  {
    id: '32',
    name: 'Grogu Plush (The Child)',
    description: 'An adorable and highly sought-after plush of Grogu. Protect him with your life.',
    price: 39.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'grogu plush',
    category: 'Toys',
    stock: 50,
  },
  {
    id: '33',
    name: 'X-Wing Pilot Helmet Replica',
    description: 'Become an ace pilot for the Rebel Alliance with this authentic X-Wing pilot helmet.',
    price: 329.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'x wing pilot helmet',
    category: 'Armor',
    stock: 9,
  },
  {
    id: '34',
    name: 'Tatooine Twin Suns Landscape Print',
    description: 'A beautiful art print capturing the iconic twin suns setting over the deserts of Tatooine.',
    price: 59.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'tatooine sunset',
    category: 'Decor',
    stock: 25,
  },
  {
    id: '35',
    name: 'Obi-Wan Kenobi\'s Jedi Robes (Replica)',
    description: 'The humble and traditional robes of Jedi Master Obi-Wan Kenobi. Perfect for desert wanderings.',
    price: 189.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'obi wan robes',
    category: 'Apparel',
    stock: 12,
  },
  {
    id: '36',
    name: 'Carbonite Freezing Chamber Diorama',
    description: 'A detailed diorama of the iconic carbon-freezing chamber from Cloud City. Han Solo figure optional.',
    price: 229.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'carbonite chamber diorama',
    category: 'Collectibles',
    stock: 7,
  },
  {
    id: '37',
    name: 'IG-11 Assassin Droid Action Figure',
    description: 'The deadly and efficient IG-series assassin droid. Programmed for termination or nursing.',
    price: 44.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'ig11 droid',
    category: 'Action Figures',
    stock: 18,
  },
  {
    id: '38',
    name: 'Wampa Fur Rug (Synthetic)',
    description: 'Add a touch of Hoth to your dwelling with this luxurious (and cruelty-free) Wampa fur rug.',
    price: 199.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'wampa rug',
    category: 'Homeware',
    stock: 10,
  },
  {
    id: '39',
    name: 'Mace Windu\'s Purple Lightsaber Hilt',
    description: 'The unique amethyst-bladed lightsaber hilt of the formidable Jedi Master Mace Windu.',
    price: 309.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'mace windu lightsaber',
    category: 'Weaponry',
    stock: 5,
  },
  {
    id: '40',
    name: 'Hoth Rebel Trooper Cold Weather Gear Set',
    description: 'Stay warm on icy planets with this complete cold weather gear set for Rebel Troopers.',
    price: 259.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'hoth rebel gear',
    category: 'Apparel',
    stock: 11,
  }
];

export const mockUsers: User[] = [
  {
    id: 'user123',
    email: 'sithlord@empire.gov',
    name: 'Darth User',
    avatarUrl: 'https://placehold.co/100x100.png?text=DU',
    joinDate: new Date(Date.now() - 86400000 * 30).toISOString(), // 30 days ago
    isAdmin: false,
  },
  {
    id: 'adminUser001',
    email: 'admin@empire.com', // Admin user
    name: 'Grand Moff Admin',
    avatarUrl: 'https://placehold.co/100x100.png?text=GA',
    joinDate: new Date(Date.now() - 86400000 * 100).toISOString(), // 100 days ago
    isAdmin: true,
  },
  {
    id: 'user456',
    email: 'rebelscum@alliance.org',
    name: 'Leia Organa',
    avatarUrl: 'https://placehold.co/100x100.png?text=LO',
    joinDate: new Date(Date.now() - 86400000 * 15).toISOString(), // 15 days ago
    isAdmin: false,
  },
  {
    id: 'user789',
    email: 'scoundrel@outer.rim',
    name: 'Han Solo',
    avatarUrl: 'https://placehold.co/100x100.png?text=HS',
    joinDate: new Date(Date.now() - 86400000 * 5).toISOString(), // 5 days ago
    isAdmin: false,
  }
];


export const mockOrders: Order[] = [
  {
    id: 'order001',
    userId: 'user123', // Darth User
    date: new Date(Date.now() - 86400000 * 7).toISOString(), // 7 days ago
    items: [
      { productId: '1', name: 'Sith Lord Meditation Chamber (Miniature)', quantity: 1, price: 199.99 },
      { productId: '6', name: 'Set of Imperial Cog Coasters', quantity: 2, price: 29.99 },
    ],
    totalAmount: 199.99 + (29.99 * 2),
    status: 'Delivered',
    shippingAddress: {
      street: '1 Death Star Avenue',
      city: 'Imperial Center',
      postalCode: 'DS1',
      country: 'Coruscant',
    },
  },
  {
    id: 'order002',
    userId: 'user123', // Darth User
    date: new Date(Date.now() - 86400000 * 2).toISOString(), // 2 days ago
    items: [
      { productId: '10', name: 'TIE Fighter Pilot Helmet Replica', quantity: 1, price: 349.99 },
    ],
    totalAmount: 349.99,
    status: 'Shipped',
    shippingAddress: {
      street: '1 Death Star Avenue',
      city: 'Imperial Center',
      postalCode: 'DS1',
      country: 'Coruscant',
    },
  },
  {
    id: 'order003',
    userId: 'user456', // Leia Organa
    date: new Date(Date.now() - 86400000 * 5).toISOString(), // 5 days ago
    items: [
      { productId: '21', name: 'Luke Skywalker\'s Lightsaber Hilt (ROTJ)', quantity: 1, price: 289.99 },
      { productId: '28', name: 'Rebel Alliance Insignia Necklace', quantity: 1, price: 49.99 },
    ],
    totalAmount: 289.99 + 49.99,
    status: 'Processing',
    shippingAddress: {
      street: 'Rebel Base, Hangar Bay 7',
      city: 'Yavin IV',
      postalCode: 'REB01',
      country: 'Yavin System',
    },
  },
  {
    id: 'order004',
    userId: 'user789', // Han Solo
    date: new Date(Date.now() - 86400000 * 1).toISOString(), // 1 day ago
    items: [
      { productId: '24', name: 'Han Solo\'s DL-44 Heavy Blaster Pistol Prop', quantity: 1, price: 249.99 },
      { productId: '22', name: 'Millennium Falcon Model Kit', quantity: 1, price: 179.99 },
    ],
    totalAmount: 249.99 + 179.99,
    status: 'Pending',
    shippingAddress: {
      street: 'Docking Bay 94',
      city: 'Mos Eisley',
      postalCode: 'ME94',
      country: 'Tatooine',
    },
  },
  {
    id: 'order005',
    userId: 'adminUser001', // Grand Moff Admin
    date: new Date(Date.now() - 86400000 * 10).toISOString(), // 10 days ago
    items: [
      { productId: '3', name: "Darth Vader's Helmet Replica (Wearable)", quantity: 1, price: 499.99 },
    ],
    totalAmount: 499.99,
    status: 'Delivered',
    shippingAddress: {
      street: 'Imperial Palace, Office of the Grand Moff',
      city: 'Imperial City',
      postalCode: 'COR77',
      country: 'Coruscant',
    },
  }
];
